version: "3.9"

services:
  app:
    build: .
    container_name: collar-backend
    ports:
      - "3005:3005"
      - "5555:5555"  # Expose Prisma Studio on the same container
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["/bin/sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run build && npm run start"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
