version: "3.9"

services:
  app:
    build: .
    container_name: collar-backend-db-1
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["/bin/sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  prisma-studio:
    image: node:18
    container_name: prisma_studio
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: ["/bin/sh", "-c", "npm install -g prisma && prisma studio"]
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
